--create database fakultet2;
--use fakultet2;
--create table fakulteti(
--ime varchar(50),
--adresa varchar(50),
--brojstudenata int
--);
--create table studenti(
--ime varchar(50),
--prezime varchar(50),
--godinastudija int
--);
--create table kolegiji(
--nazivkolegija varchar(50),
--predmet varchar(50),
--profesor varchar(50)
--);