--create database projekti;
--use projekti
--create table zaposlenik(
--sifra int,
--nadredeni int,
--ime varchar(50),
--prezime varchar(50),
--datumrodjenja datetime,
--placa decimal(18,2),
--odjel int
--);
--create table sudjeluje(
--zaposlenik int,
--projekt int,
--datumpristupanja datetime
--);
--create table projekt(
--sifra int,
--naziv varchar(50),
--datumpocetka datetime,
--datumkraja datetime
--);
--create table odijel(
--sifra int,
--naziv varchar(50)
--);