use master;
GO
DROP DATABASE IF EXISTS WEBSHOP;
GO
CREATE DATABASE WEBSHOP;
GO
USE WEBSHOP;
CREATE TABLE PROIZVODI(
SIFRA INT NOT NULL PRIMARY KEY IDENTITY (1,1),
NAZIV VARCHAR(50) NOT NULL,
DATUM_NABAVE DATETIME,
CIJENA DECIMAL(18,2),
AKTIVAN BIT 
);

CREATE TABLE STAVKE(
RACUN INT NOT NULL,
PROIZVOD INT NOT NULL,
KOLICINA INT NOT NULL,
CIJENA DECIMAL(18,2)
);

CREATE TABLE RACUNI(
SIFRA INT NOT NULL PRIMARY KEY IDENTITY(1,1),
DATUM DATETIME,
KUPAC INT NOT NULL,
STATUS BIT 
);

CREATE TABLE KUPCI(
SIFRA INT NOT NULL PRIMARY KEY IDENTITY(1,1),
IME VARCHAR(50) NOT NULL,
PREZIME VARCHAR(50) NOT NULL,
ULICA VARCHAR(50),
MJESTO VARCHAR(50)
);

ALTER TABLE STAVKE ADD FOREIGN KEY(RACUN) REFERENCES PROIZVODI(SIFRA);
ALTER TABLE STAVKE ADD FOREIGN KEY (PROIZVOD) REFERENCES RACUNI(SIFRA);
ALTER TABLE RACUNI ADD FOREIGN KEY(KUPAC) REFERENCES KUPCI(SIFRA);

INSERT INTO PROIZVODI(NAZIV,DATUM_NABAVE,CIJENA,AKTIVAN)VALUES
('COCA_COLA','2024-05-17 09:00','2.09','1'),
('FANTA','2024-05-18 10:00','1.99','1')
SELECT * FROM PROIZVODI

INSERT INTO RACUNI(DATUM,KUPAC,STATUS)VALUES
('2024-06-01 11:20','1','1'),
('2024-06-02 06:35','2','1')
SELECT * FROM RACUNI

INSERT INTO KUPCI(IME,PREZIME,ULICA,MJESTO)VALUES
('HRVOJE','PULJIĆ-ILIĆ','ZVONARSKA 47','VINKOVCI'),
('DOMINIK','PULJIĆ-ILIĆ','ZVONARSKA 47','VINKOVCI')
SELECT * FROM KUPCI

INSERT INTO STAVKE(RACUN,PROIZVOD,KOLICINA,CIJENA)values
('1','1','12','2.09'),
('1','2','4','1.99'),
('2','2','7','1.99'),
('2','1','18','2.09')
SELECT * FROM STAVKE;