--create database racuni;
--use racuni
--crate table racun(
--sifra int,
--rednibroj int,
--datum datetime,
--kupac varchar(50),
--placeno bit
--);
--create table stavke racuna(
--racun int,
--artikl varchar(50),
--cijena decimal(18,2),
--kolicina int,
--popust int
--);